openapi: 3.0.1
info:
  title: colors
  description: list of colors
  version: '0.1'
servers:
  - url: 'http://colors:8080'
paths:
  /colors:
    get:
      description: List all colors
      operationId: listColors
      responses:
        '200':
          description: a list of colors with their index
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Colors"
              #examples: {"adjectives": [{"id":1,"name":"blue"}]}
      servers:
        - url: 'http://colors:8080'
    post:
      description: create a color
      operationId: createColor
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                id:
                  type: integer
            examples:
              '0':
                value: '{"name":"yellow"}'
              '1':
                value: '{"id":4}'
      responses:
        '201':
          description: color created
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://colors:8080'
    delete:
      description: delete a color
      operationId: deleteColor
      responses:
        '404':
          description: Auto generated using Swagger Inspector
          content:
            application/json; charset=utf-8:
              schema:
                type: string
              examples: {}
      servers:
        - url: 'http://colors:8080'
    servers:
      - url: 'http://colors:8080'
  /colors/{id}:
    get:
      description: get a specific color
      operationId: showColorById
      parameters:
        - name: id
          in: path
          required: true
          description: id of the color to retrieve
          schema:
            type: integer
      responses:
        '200':
          description: Successful
          content:
            application/json; charset=utf-8:
              schema:
                $ref: "#/components/schemas/Color"
              # examples: {"adjectives": [{"id":1,"name":"blue"}]}
      servers:
        - url: 'http://colors:8080'
        
components:
  schemas:
    Color:
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
  #      tag:
  #        type: string
    Colors:
      type: array
      items:
        $ref: "#/components/schemas/Color"
