---
apiVersion: v1
kind: Service
metadata:
  name: adjectives
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: adjectives
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adjectives
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adjectives
  template:
    metadata:
      labels:
        app: adjectives
    spec:
      containers:
      - name: adjectives
        image: registry.gitlab.com/sentence-application/adjectives:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
